version: '2.1'

services:
  spring-webflux-angular:
    image: spring-webflux-angular
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 3000:3000
      - 5005:5005
    